#include "Actor/Individual.h"
#include "Profession/ProfessionFactory.h"
#include "Action/GoalTree.h"
#include "Relationship/Relationship.h"
#include <algorithm>
#include <exception>

namespace Actor
{

    Individual::Individual(std::string _name,
                           Location_ptr _location,
                           Profession::Profession_ptr p,
                           bool _isMale) :
        profession(p),
        age(0),
        name(_name),
        isMale(_isMale),
        currentLocation(_location),
        goalTree()
    {
        stats[HEALTH] =         1;
        stats[SPEED] =          1;
        stats[AGILITY] =        1;
        stats[INTELLIGENCE] =   1;
        stats[DEXTERITY] =      1;
        stats[HUNGER] =         0;
        stats[FATIGUE] =        0;
    }

    float Individual::getSkillLevel(Skill::SkillType s)
    {
        try {
            /*
             * getSkillLevel from profession will return 0.0f if the lookup fails.
             * We can assume, therefore, that the exception must have been generated by the lookup
             * in the player skillMap. So return the professionSkill.
             */

            return skillMap.at(s) + profession->getSkillLevel(s);
        }
        catch (std::exception& e) {
            return profession->getSkillLevel(s);
        }

    }

    bool Individual::removeItem(Item::Item_ptr i)
    {
        if (std::find(items.begin(), items.end(), i) == items.end())
        {
            return false;
        }
        else
        {
            items.erase(std::find(items.begin(), items.end(), i));
            return true;
        }
    }

    void Individual::addRelationship(Location::Location_ptr location, Relationship::RelationshipType rel)
    {
        LocationRelationshipMap.addRelationship(location, rel);
    }

    void Individual::addRelationship(Individual_ptr individual, Relationship::RelationshipType rel)
    {
        IndividualRelationshipMap.addRelationship(individual, rel);
    }

    unsigned int Individual::calculatePriority(Individual_ptr individual, Action::GoalType goalType)
    {
        //TODO relationships can be both positive and negative, so size is not a good metric
        if (IndividualRelationshipMap.getRelationships(individual).size() != 0)
            return 10;
        return 0;
    }
}
