import os
import re
import glob
import sys
import fnmatch
import platform

env = Environment()

env.Replace(CCFLAGS = [])
Tool('mingw')(env) # Prefer MinGW over other compilers like cl.exe

env.Append(LIBPATH = ['../lib'])
env.Append(CXXFLAGS=['-Wall', '-std=c++11'])

if platform.system() == "Windows":
   env.Append(LIBS = ['pdcurses', 'jsoncpp', 'gtest'])
elif platform.system() == "Linux":
   env.Append(LIBS = ['ncurses', 'jsoncpp', 'gtest_main', 'gtest', 'pthread'])
   
env.Append(CPPPATH=['include', '../include', '.'])


object_list = []
for root, dirnames, filenames in os.walk('../scr'):
	for filename in fnmatch.filter(filenames, '*.o'):
		if filename != 'main.o':
			object_list.append(os.path.join(root, filename))
                        
matches = Glob('*.cpp')
for match in matches:
	object_list.append(env.Object(target="obj/" + os.path.splitext(str(match))[0] + '.o', source=match))

if platform.system() == "Windows":
   env.Program(target = "tests.exe", source = object_list)
elif platform.system() == "Linux":
   env.Program("tests.out", source = object_list)
